baseURL = 'https://www.minmax.sk/'
languageCode = 'sk-sk'
title = 'MinMax'
theme = 'PaperMod'
defaultContentLanguage = 'sk'
#googleAnalytics = 'G-LG2BD3ZMBK'

[params]
#env = "production"
title = 'MinMax'
description = "Vybavenie pre vašu domácnosť a koníčky na úrovni"
#author = "RickRacs"
DateFormat = "2. January,  2006"
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = true
ShowBreadCrumbs = false
ShowCodeCopyButtons = false
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = false
#Table of contents do budúcna môže byť
showtoc = false
tocopen = false


[params.analytics.google]
SiteVerificationTag = "3b7LwzVW5vazkwnu9dXMhFCnb4bOKRPzTgWc-NZKRWI"


  [params.label]
  text = "MinMax"
  icon = "/thinking-man-tn.png"
  iconHeight = 45


[params.homeInfoParams]
  Title = "MinMax"
  Content = "Návody na optimalizáciu svojich rozhodnutí."

  [[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com/minmax.sk"
 
 
  [[params.socialIcons]]
    name = "goodreads"
    url = "https://www.goodreads.com/user/show/52913823-richard-r"
 
  [[params.socialIcons]]
    name = "spotify"
    url = "https://open.spotify.com/user/razon."


    [params.cover]
  hidden = false
  hiddenInList = true
  hiddenInSingle = true

  
[[menu.main]]
identifier = "categories"
name = "Kategórie"
url = "/categories/"
weight = 10



[[menu.main]]
identifier = "archives"
name = "Archív"
url = "/archives/"
weight = 20

